# Generated by Django 3.2.9 on 2022-03-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('by', models.CharField(max_length=500, null=True)),
                ('title', models.CharField(max_length=500, null=True)),
                ('time', models.DateTimeField(null=True)),
                ('type', models.CharField(default='story', max_length=500)),
                ('url', models.CharField(max_length=500, null=True)),
                ('descendants', models.IntegerField(null=True)),
                ('score', models.IntegerField(null=True)),
                ('kids', models.JSONField(null=True)),
                ('deleted', models.BooleanField(null=True)),
                ('dead', models.BooleanField(null=True)),
                ('parent', models.IntegerField(null=True)),
                ('text', models.TextField(null=True)),
                ('parts', models.JSONField(null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
