# Generated by Django 3.2.9 on 2021-12-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('by', models.CharField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('type', models.CharField(blank=True, max_length=500, null=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('descendants', models.IntegerField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('kids', models.JSONField(blank=True, null=True)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('dead', models.BooleanField(blank=True, null=True)),
                ('parent', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
