# Generated by Django 3.2.9 on 2021-12-09 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='time',
        ),
    ]
