# Generated by Django 3.2.9 on 2021-12-16 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_rename_news_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-id']},
        ),
    ]
